spring.application.name=analiza-prodaje
server.port=8086

spring.cassandra.contact-points=${SPRING_CASSANDRA_CONTACT_POINTS:cassandradb}
spring.cassandra.port=${SPRING_CASSANDRA_PORT:9042}
spring.cassandra.keyspace-name=${SPRING_CASSANDRA_KEYSPACE_NAME:analiza_prodaje}
spring.cassandra.local-datacenter=${SPRING_CASSANDRA_LOCAL_DATACENTER:datacenter1}
spring.cassandra.schema-action=${SPRING_CASSANDRA_SCHEMA_ACTION:CREATE_IF_NOT_EXISTS}

spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:redisdb}
spring.data.redis.port=${REDIS_PORT:6379}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}